[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
remappings = [
    'ERC721A/=lib/ERC721A/contracts/',
    'ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'openzeppelin/=lib/openzeppelin-contracts/contracts/',
]

# Configures permissions for cheatcodes that touch the filesystem like `vm.readFile`
fs_permissions = [{ access = "read-write", path = "./script/input" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
